language: python
python:
  - "3.8"

services:
  - docker

before_script:
  - touch .env
  - echo POSTGRES_DB=$POSTGRES_DB >> .env
  - echo POSTGRES_USER=$POSTGRES_USER >> .env
  - echo POSTGRES_PASSWORD=$POSTGRES_PASSWORD >> .env
  - pip install docker-compose

script:
  - docker-compose run web sh -c "python manage.py test && flake8"
